### ISSUE TITLE
Urllib2 -> urllib.request

### ISSUE THREAD

**Issue by jdelamare** [Ucnt/docker-flask-nginx-uwsgi#4]
Correct me if I'm wrong, but line 22 in flaskwebpage.py should be moved from 
`from urllib2 import urlopen`
to 
`from urllib.request import urlopen`

**Comment by Ucnt** [comment]
Hmmm.....Odd.  I have the container running at home and it should be throwing an error.  

You're right.  Python3 is urllib.request.

Doing a quick build and test before modifying.  Thanks!

**Comment by Ucnt** [comment]
Oh, silly me.  I am using a different method in my "personal" version of the flask app, below.

This returns the IP address the server gets vs the IP from icanhazip.

def get_client_ip():
    """Gets client IP from xforward for or remote address if not proxied"""
    if request.headers.getlist("X-Forwarded-For"):
        return request.headers.getlist("X-Forwarded-For")[0]
    else:
return request.remote_addr

I'll update with your correction and add this second method, depending on how someone wants to get it.

**Comment by jdelamare** [comment]
Whatever you think is best!

Cheers.
